// blox-sveltekit/src/lib/header/Header.svelte
<script lang="ts">
	import { page } from '$app/stores';
import Button from './Button.svelte';
import DropdownButton from './DropdownButton.svelte';
</script>

<header>
	<DropdownButton title={"Play"}>
		<Button>Multiplayer</Button>
		<Button>Singleplayer</Button>
		<Button>Custom</Button>
		<Button>Opener</Button>
	</DropdownButton>
	<DropdownButton title={"Other"} className="block sm:hidden">
		<Button>Leaderboard</Button>
		<Button>Map Maker</Button>
		<Button>About</Button>
		<Button>Discord</Button>
	</DropdownButton>
	<Button className="hidden sm:block">Leaderboard</Button>
	<Button className="hidden sm:block">Map Maker</Button>
	<Button className="hidden sm:block">About</Button>
	<Button className="hidden sm:block">Discord</Button>
	<DropdownButton title={"Profile"}>
		<Button>Times</Button>
		<Button>Account</Button>
		<Button>Log out</Button>
	</DropdownButton>
</header>

<style>
	header {
		display: flex;
		justify-content: center;
		color: white;
		background-color: #95f;
		z-index: 4;
	}

	@media (min-width: 480px) {
		header {
			flex-direction: row;
			--scale: 1;
		}
	}
</style>

// blox-nextjs/src/components/header.tsx
import type { NextPage } from "next";
import useWindowDimensions from "../hooks/useWindowDimensions";
import { trpc } from "../utils/trpc";
import HeaderButton from "./headerbutton";
import HeaderDropdown from "./headerdropdown";

export default function Header() {
  const { height, width} = useWindowDimensions();

  return (
    <>
      <div className="flex justify-center items-center bg-purple-600 text-white">
        <HeaderDropdown href="" title="Play">
          <HeaderButton href="">Multiplayer</HeaderButton>
          <HeaderButton href="">Singleplayer</HeaderButton>
          <HeaderButton href="">Custom</HeaderButton>
          <HeaderButton href="">Opener</HeaderButton>
        </HeaderDropdown>
        <HeaderButton href="" className="hidden sm:block ">Leaderboards</HeaderButton>
        <HeaderButton href="" className="hidden sm:block ">Map Maker</HeaderButton>
        <HeaderButton href="" className="hidden sm:block ">About</HeaderButton> 
        <HeaderDropdown href="" title="Other" className="sm:hidden block">
          <HeaderButton href="">Leaderboards</HeaderButton>
          <HeaderButton href="">Map Maker</HeaderButton>
          <HeaderButton href="">About</HeaderButton>
        </HeaderDropdown>
        <HeaderDropdown href="" title="Profile">
          <HeaderButton href="">Times</HeaderButton>
          <HeaderButton href="">Account</HeaderButton>
          <HeaderButton href="">Log Out</HeaderButton>
        </HeaderDropdown>
      </div>
    </>
  )
}
