// blox-sveltekit/src/routes/index.svelte
<script context="module" lang="ts">
	export const prerender = true;
</script>

<script lang="ts">
	import Button from '$lib/Button.svelte';
</script>

<svelte:head>
	<title>Home</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<div class="section">
	<div class="modes">
		<h1>Modes</h1>
		<div class="mode-list">
			<Button>Default</Button>
			<Button>40 Lines</Button>
			<Button>Hyper</Button>
			<Button>Digger</Button>
		</div>
		<div>
			Singleplayer Tools
			<input type="number" value="0" min="0" max="10000"/>
		</div>
		<div>
			Stats
			<p>
				time: 10.001<br/>
				pps: 3.4<br/>
				apm: 35.6<br/>
				lines: 4
			</p>
		</div>
	</div>
	<div class="main">
		<div class="left-game">
			<div class="hold">hold</div>
			<div>Settings</div>
		</div>
		<div class="game">
			<div class="canvas">
				game
			</div>
		</div>
		<div class="game-right">
			<div class="queue">
				queue
			</div>
		</div>
	</div>
	<div class="aside">
		Opponents
	</div>
	<div class="chat">
		<h2>Chat</h2>
		<div>blah blah</div>
		<input placeholder="type chat here"/>
	</div>
</div>

<style>
	.section {
		display: flex;
		flex-direction: column;
		/* justify-content: center; */
		/* align-items: center; */
		flex: 1;
		flex-wrap: wrap;
		--scale: 0.5;
	}

	.modes {
		display: flex;
		flex-direction: column;
		margin: 0px 4px;
		padding: 4px 0px;
		order: 1;
	}

	.modes div {
		padding: 16px;
		border-radius: 8px;
		display: flex;
		flex-direction: column;
		background-color: var(--card-color);
		margin-bottom: 4px;
	}

	.mode-list {
		display: flex;
		flex-direction: column;
		padding: 8px !important;
	}

	.main {
		padding: 16px;
		display: flex;
		justify-content: center;
		order:0;
	}

	.hold {
		margin-top: 2px;
		width: calc(128px * var(--scale));
		height: calc(128px * var(--scale));
		/* border: 2px solid; */
	}

	.canvas {
		width: calc(320px * var(--scale));
		height: calc(640px * var(--scale));
		border: 2px solid;
	}

	.queue {
		margin-top: 2px;
		margin-left: calc(32px * var(--scale));
		width: calc(128px * var(--scale));
		height: calc(320px * var(--scale));
		/* border: 2px solid; */
	}

	.aside {
		flex-grow: 1;
		margin: 4px;
		order: 3;
	}

	.chat {
		position: static;
		margin: 4px;
		right: 8px;
		bottom: 8px;
		padding: 8px;
		border-radius: 8px;
		background-color: var(--card-color);
		order: 4;
	}

	h1 {
		margin: 8px 0px;
	}

	@media (min-width: 640px) {
		.section {
			flex-direction: row;
			--scale: 1;
		}
		.chat {
			position: sticky;
		}
		.main {
			order:2;
		}
	}
</style>

// blox-qwik/src/routes/index.tsx
import { component$, useStyles$ } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import { Link } from '@builder.io/qwik-city';
import Button from '~/components/buttons/button';
import Header from '~/components/header/header';
// import styles from '../global.css';

export default component$(() => {
  // useStyles$(styles);
  return (
    <>
      <div className="w-full flex flex-col flex-wrap sm:flex-row text-white bg-gray-900">
        <div className="order-0 flex flex-col pt-4 mx-2">
          <div className="p-4 mb-2 text-3xl">Modes</div>
          <div className="p-4 mb-2 bg-gray-700 rounded text-center flex flex-col">
            <Button className="block">Default</Button>
            <Button className="block">40 lines</Button>
            <Button className="block">Hyper</Button>
            <Button className="block">Digger</Button>
          </div>
          <div className="p-4 mb-2 bg-gray-700 rounded">
            <h1 className="text-lg">Singleplayer tools</h1>
            Reset time <input className="text-black" type="number" min="0" max="10000" value="0"/>
          </div>
          <div className="p-4 mb-2 bg-gray-700 rounded">
            <h1 className="text-lg">stats</h1>
            <p className="text-sm">
              PPS: 0<br/>
              APM: 0<br/>
              lines: 0<br/>
            </p>
          </div>
        </div>
        <div className="sm:order-1 order-[-1]">
          <div className="p-5 flex">
            <div className="sm:w-[128px] w-[64px]">Hold</div>
            <div className="sm:w-[320px] sm:h-[640px] w-[160px] h-[320px]">Game</div>
            <div className="sm:w-[160px] w-[80px]">Queue</div>
          </div>
        </div>
        <div className="order-2 flex-grow m-2 sm:m-0">Opponents</div>
        <div className="p-4 bg-gray-700 rounded sm:absolute right-3 bottom-3 static m-2">
        <h1>Chat</h1>
        <div>
          {/* <h1 className="text-center text-4xl">{hello.data?.greeting}</h1> */}
        </div>
      </div>
      </div>
    </>
  );
});

export const head: DocumentHead = {
  title: 'Blox',
};
