// blox-nextjs/src/components/headerdropdown.tsx
import HeaderButton from "./headerbutton";

type HeaderDropdownProps = {
  children: React.ReactNode;
  href: string;
  title: string;
  className?: string;
}

export default function HeaderDropdown({children, href, title, className}:HeaderDropdownProps) {
  return (
    <div className={"relative group "+(className ?? '')}>
      <HeaderButton href={href}>{title}</HeaderButton>
      <div className="absolute top-full hidden bg-gray-800 group-hover:block group-hover:drop-shadow">
        {children}
      </div>
    </div>
  )
}

// blox-qwik/src/components/header/headerdropdown.tsx
import { component$, Slot } from '@builder.io/qwik';
import { HeaderButton } from './headerbutton';

type HeaderDropdownProps = {
  href: string;
  title: string;
  className?: string;
}

export const HeaderDropdown = component$(({href, title, className}:HeaderDropdownProps) => {
  return (
    <div className={"relative group "+(className ?? '')}>
      <HeaderButton href={href}>{title}</HeaderButton>
      <div className="absolute top-full hidden bg-gray-800 group-hover:block group-hover:drop-shadow">
        <Slot/>
      </div>
    </div>
  )
});
