// blox-nextjs/src/components/headerbutton.tsx
import Link from "next/link";

type HeaderButtonProps = {
  children: React.ReactNode;
  href?: string;
  className?: string;
}

export default function HeaderButton({children, href, className}:HeaderButtonProps) {
  return (
    <>
      <Link href={href ?? ""}>
        <a className={"p-4 block duration-100 hover:bg-purple-500 "+(className ?? '')}>{children}</a>
      </Link>
    </>
  )
}

// blox-qwik/src/components/header/headerbutton.tsx
import { component$, Slot } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';

type HeaderButtonProps = {
  href?: string;
  className?: string;
}

export const HeaderButton = component$<HeaderButtonProps>(({href, className}) => {
  return (
    <>
      <Link href={href ?? ""}>
        <a className={"p-4 block duration-100 hover:bg-purple-500 cursor-pointer "+(className ?? '')}><Slot/></a>
      </Link>
    </>
  )
});
